
<div class="span9">
    <h1 class="page-header"><?php echo $this->title ?></h1>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>A&ntilde;o</th>
                <th>URL imagen</th>
                <th>Editorial</th>
                <th>Editar</th>
                <th>Eliminar</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->data as $collection): ?>
                <tr>
                    <td><?php echo $this->escape($collection->getName()) ?></td>
                    <td><?php echo $this->escape($collection->getYear()) ?></td>
                    <td>
                    	<a href="<?php echo $this->escape($collection->getImageUrl()) ?>">
                    		<?php echo $this->escape($collection->getImageUrl()) ?>
                    	</a>
                    </td>
                    <td>
                    	<a href="<?php echo $this->baseUrl() ?>/admin/editorial/update/id/<?php echo $this->escape($collection->getEditorial()->getId()) ?>">
                    		<?php echo $this->escape($collection->getEditorial()->getName()) ?>
                    	</a>
                    </td>
                    <td>
                    	<a href="<?php echo $this->baseUrl() ?>/admin/collection/update/id/<?php echo $collection->getId() ?>" >
                    	<i class="icon-edit"></i>
                    	</a>
                    </td>  
                    <td>
                    	<a href="<?php echo $this->baseUrl() ?>/admin/collection/delete/id/<?php echo $collection->getId() ?>" 
                    		onclick="return confirm('&iquest;Est&aacute; seguro que desea eliminar esta editorial?');">
                    		<i class="icon-remove"></i>
                    	</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>    
</div>
