
<div class="span9">
    <h1 class="page-header"><?php echo $this->title ?></h1>
    <div>
		<form id="filterEditorialForm" name="filterEditorialForm" method="get" action="<?php echo $this->baseUrl() ?>/admin/collection/list" class="form-inline pull-right">
			<label for="editorial_id">Filtrar por: </label>
			<select name="editorial_id" id="editorial_id">
				<option value="0" label="Todas las editoriales" style="font-weight: bold;"
					<?php if($this->editorial == 0): ?>
						selected="selected"
					<?php endif; ?>
				>
					Todas las editoriales
				</option>
				<?php foreach ($this->editorials as $editorial): ?>
					<option value="<?php echo $editorial->getId() ?>" label="<?php echo $editorial->getName() ?>"
						<?php if($this->editorial == $editorial->getId()): ?>
							selected="selected"
						<?php endif; ?>						
					>
						<?php echo $editorial->getName() ?>
					</option>
				<?php endforeach; ?>
			</select>
			<input type="submit" value="Filtrar" class="btn btn-inverse">
		</form>
    </div>
    
    <?php if (count($this->data) == 0): ?>
    	<div class="alert" style="clear: both;">
    		<p><?php echo $this->msgempty ?></p>
    	</div>
    	
    <?php else: ?>
	    <table class="table table-bordered">
	        <thead>
	            <tr>
	                <th>Nombre</th>
	                <th>A&ntilde;o</th>
	                <th>URL imagen</th>
	                <th>Editorial</th>
	                <th>Ver cromos</th>
	                <th>Editar</th>
	                <th>Eliminar</th>
	            </tr>
	        </thead>
	        <tbody>
	            <?php foreach ($this->data as $collection): ?>
	                <tr>
	                    <td><?php echo $this->escape($collection->getName()) ?></td>
	                    <td><?php echo $this->escape($collection->getYear()) ?></td>
	                    <td>
	                    	<a href="<?php echo $this->escape($collection->getImageUrl()) ?>">
	                    		<?php echo $this->escape($collection->getImageUrl()) ?>
	                    	</a>
	                    </td>
	                    <td>
	                    	<a href="<?php echo $this->baseUrl() ?>/admin/editorial/update/id/<?php echo $this->escape($collection->getEditorial()->getId()) ?>">
	                    		<?php echo $this->escape($collection->getEditorial()->getName()) ?>
	                    	</a>
	                    </td>
	                    <td>
	                    	<a href="<?php echo $this->baseUrl() ?>/admin/sticker/list/collection_id/<?php echo $collection->getId() ?>">
								<i class="icon-list"></i>
							</a>
	                    </td>
	                    <td>
	                    	<a href="<?php echo $this->baseUrl() ?>/admin/collection/update/id/<?php echo $collection->getId() ?>" >
	                    		<i class="icon-edit"></i>
	                    	</a>
	                    </td>  
	                    <td>
	                    	<a href="<?php echo $this->baseUrl() ?>/admin/collection/delete/id/<?php echo $collection->getId() ?>" 
	                    		onclick="return confirm('&iquest;Est&aacute; seguro que desea eliminar esta colecci&oacute;n?');">
	                    		<i class="icon-remove"></i>
	                    	</a>
	                    </td>
	                </tr>
	            <?php endforeach; ?>
	        </tbody>
	    </table>
	    <?php
			echo $this->paginationControl($this->data, 'Sliding', 'pagination.phtml', array("editorial_id" => $this->editorial));
		?>
	<?php endif; ?>
</div>    
