
<div class="span9">
    <h1 class="page-header"><?php echo $this->title ?></h1>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Prioridad</th>
                <th>URL imagen</th>
                <th>Editar</th>
                <th>Eliminar</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->data as $editorial): ?>
                <tr>
                    <td><?php echo $this->escape($editorial->getName()); ?></td>
                    <td><?php echo $this->escape($editorial->getPriority()); ?></td>
                    <td>
                    	<a href="<?php echo $this->escape($editorial->getImageUrl()) ?>">
                    		<?php echo $this->escape($editorial->getImageUrl()); ?>
                    	</a>
                    </td>
                    <td>
                    	<a href="<?php echo $this->baseUrl() ?>/admin/editorial/update/id/<?php echo $editorial->getId(); ?>" >
                    	<i class="icon-edit"></i>
                    	</a>
                    </td>  
                    <td>
                    	<a href="<?php echo $this->baseUrl() ?>/admin/editorial/delete/id/<?php echo $editorial->getId(); ?>" 
                    		onclick="return confirm('&iquest;Est&aacute; seguro que desea eliminar esta editorial?');">
                    		<i class="icon-remove"></i>
                    	</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <div class="alert">
		<h3>Prioridades</h2>   
		<ul>
			<li>M&iacute;nima: <?php echo $this->minPriority ?></li>
			<li>M&aacute;xima: <?php echo $this->maxPriority ?></li>
		</ul>
    </div>
</div>    
</div>
