
<div class="span9">
    <h1 class="page-header"><?php echo $this->title ?></h1>   
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Prioridad</th>
                <th>URL imagen</th>
                <th >Editar</th>
                <th >Eliminar</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->data as $editorial): ?>
                <tr>
                    <td><?php echo $this->escape($editorial->name); ?></td>
                    <td><?php echo $this->escape($editorial->priority); ?></td>
                    <td>
                    	<a href="<?php echo $this->escape($editorial->imageUrl) ?>">
                    		<?php echo $this->escape($editorial->imageUrl); ?>
                    	</a>
                    </td>
                    <td><a href="<?php echo $this->baseUrl() ?>/admin/editorial/update/id/<?php echo $editorial->id; ?>" ><i class="icon-edit"></i></a></td>  
                    <td><a href="<?php echo $this->baseUrl() ?>/admin/editorial/delete/id/<?php echo $editorial->id; ?>" ><i class="icon-remove"></i></a></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>    
</div>
