<div class="span9">
	<div class="entrada" id="formulario">
		<h1 class="page-header">Editar Editorial</h1>
			<form action="<?php echo $this->baseUrl() ?>/admin/editorial/update" method="post">
				<div class=" alert-error">
                	<?php 
                		if (!empty($this->message))
							echo $this->message
					?> 
				</div>
                <ul>
                    <li> 
                        <label for="name">Nombre</label>
                        <input type="text" class="input-largo" required="required" name="name" id="name" 
                        	value="<?php echo $this->editorial->getName() ?>" />
                    </li>
                    <li>
                        <label for="priority">Prioridad</label>
                        <select required="required" name="priority" id="priority">
                        	<?php 
                        		$minPriority = 1;
                        		$maxPriority = 5;
                        		for ($i = $minPriority; $i <= $maxPriority; $i++): 
                        	?>
                        		<option value="<?php echo $i ?>"
                        			<?php if ($i == $this->editorial->getPriority()): ?>
                        				selected="selected"
                        			<?php endif; ?>
                        		>
                        			<?php echo $i ?>
                        			<?php 
                        				if ($i == $minPriority) echo " - Menor prioridad";
                        				if ($i == $maxPriority) echo " - Mayor prioridad";
                        			?>
                        		</option>
                        	<?php endfor; ?>
                        </select>
                    </li>
                    <li>
                        <label for="imageUrl">URL de la imagen</label>
                        <input type="text" class="input-largo" required="required" name="imageUrl" id="imageUrl"
                        	value="<?php echo $this->editorial->getImageUrl() ?>" />
                    </li>

                    <li>
                    	<input type="hidden" required="required" name="id" id="id"
                    		value="<?php echo $this->editorial->getId() ?>" />
                    	<input type="submit" class="btn btn-large btn-inverse" value="Editar" /> 
                    </li>  
                </ul>
			</form>
			                            
		</div>  
	</div>    
        
</div>