<!-- http://cssdeck.com/item/271/twitter-bootstrap-pagination-and-pager -->

<div class="pagination pagination-centered">
    <div>
		<ul>
	        <!-- First page link -->
			<?php if (isset($this->previous)): ?>
		      	<li>
					<a href="<?= $this->urlParameters(array('page' => $this->first)); ?>">&laquo;</a>
				</li>			            
			<?php else: ?>
				<li class="disabled">
					<a href="#">&laquo;</a>
				</li>
			<?php endif; ?>
	    
	    
	        <!-- Previous page link -->
			<?php if (isset($this->previous)): ?>
				<li>
					<a href="<?= $this->urlParameters(array('page' => $this->previous)); ?>">&lt;</a>
				</li>
			<?php else: ?>
				<li class="disabled">
					<a href="#">&lt;</a>
				</li>
			<?php endif; ?>
	        
	        
	        <!-- Numbered page links -->
	        <?php foreach ($this->pagesInRange as $page): ?>
	            <?php if ($page == $this->current): ?>
	            	<li class="active">
	                	<a href="#"><?= $page; ?></a>
	                </li>
	            <?php else: ?>
	            	<li>
	            		<a href="<?= $this->urlParameters(array('page' => $page)); ?>"><?= $page; ?></a>
	            	</li>
	            <?php endif; ?>
	        <?php endforeach; ?>
	        

	        <!-- Next page link -->
			<?php if (isset($this->next)): ?>
				<li>
					<a href="<?= $this->urlParameters(array('page' => $this->next)); ?>">&gt;</a>
				</li>
			<?php else: ?>
				<li class="disabled">
					<a href="#">&gt;</a>
				</li>
			<?php endif; ?>
	        
	        
	        <!-- Last page link -->
			<?php if (isset($this->next)): ?>
				<li>
					<a href="<?= $this->urlParameters(array('page' => $this->last)); ?>">&raquo;</a>
				</li>				
			<?php else: ?>
				<li class="disabled">
					<a href="#">&raquo;</a>
				</li>
			<?php endif; ?>
        </ul>
    </div>
 </div>