<div class="row">
    <div class="span12">
        <div id="login">
            <h2><em><?php echo $this->title ?></em> </h2>  
            <div id="main-login">
                <div class="linea"></div>

                <form action="<?php echo $this->baseUrl("/admin/login") ?>" method="post">
                    <div class=" alert-error">
                    	<?php 
                    		if (!empty($this->message))
    							echo $this->message
    					?> 
    				</div>
                    <ul>
                        <li> 
                            <label for="user">Usuario</label>
                            <input type="text" class="input-largo" required="required" name="user" id="user" />
                        </li>
                        <li>
                            <label for="pass">Contrase&ntildea</label>
                            <input type="password" class="input-largo" required="required" name="pass" id="pass" />
                        </li>

                        <li>
                        	<input type="submit" class="btn btn-large btn-inverse" value="Entrar" /> 
                        </li>  
                    </ul>
                </form> 
            </div>
        </div><!-- fin login -->
    </div>

</div><!-- fin row -->

