
<div class="span9">
    <h1 class="page-header"><?php echo $this->title ?></h1>
    <?php if (count($this->data) == 0): ?>
		<div class="alert">
    		<p><?php echo $this->msgempty ?></p>
    	</div>
    	
    <?php else: ?>
	    <div class="image-list">
	    	<ul>
	    		<?php for($i=0; $i<20; $i++): ?>
	    		<li>
	    			<img src="<?php echo $this->baseUrl() ?>/images/albums/1.jpg">
	    			<div class="image-details">
	    				<a href="#"><i class="icon-remove"></i> Eliminar</a>
	    			</div>
	    		</li>
	    		<li>
	    			<img src="<?php echo $this->baseUrl() ?>/images/albums/2.jpg">
	    			<div class="image-details">
	    				<a href="#"><i class="icon-remove"></i> Eliminar</a>
	    			</div>
	    		</li>
	    		<li>
	    			<img src="<?php echo $this->baseUrl() ?>/images/albums/3.jpg">
	    			<div class="image-details">
	    				<a href="#"><i class="icon-remove"></i> Eliminar</a>
	    			</div>
	    		</li>
	    		<li>
	    			<img src="<?php echo $this->baseUrl() ?>/images/albums/4.jpg">
	    			<div class="image-details">
	    				<a href="#"><i class="icon-remove"></i> Eliminar</a>
	    			</div>
	    		</li>
	    		<li>
	    			<img src="<?php echo $this->baseUrl() ?>/images/albums/5.jpg">
	    			<div class="image-details">
	    				<a href="#"><i class="icon-remove"></i> Eliminar</a>
	    			</div>
	    		</li>
	    		<?php endfor; ?>
	    	</ul>
	    </div>
	    <?php
			//echo $this->paginationControl($this->data, 'Sliding', 'pagination.phtml');
		?>
	<?php endif; ?>
</div>
