<?php echo $this->doctype(); ?> 
<html lang="es">
	<head>
    	<meta charset="utf-8">
    
		<?php echo $this->headTitle() ?>   
    	
    	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    	
     	<style type="text/css">
      		body {
      			padding-bottom: 40px;
        		padding-top: 60px;
      		}
      		.sidebar-nav {
        		padding: 9px 0;
      		}
    	</style>

		<?php echo $this->headLink()->appendStylesheet($this->baseUrl()."/css/bootstrap.css","screen"); ?>
		<?php echo $this->headLink()->appendStylesheet($this->baseUrl()."/css/bootstrap-responsive.css","screen"); ?>
		<?php echo $this->headLink()->appendStylesheet($this->baseUrl()."/css/admin.css","screen"); ?>
		<?php echo $this->headScript()->appendFile($this->baseUrl()."/js/admin.js"); ?>
    </head>
	<body>
    
 		<!-- nav -->   
 		<div class="navbar navbar-fixed-top">
 			<div class="navbar-inner">
 				<div class="container-fluid">
					<a class="brand" href="<?php echo $this->baseUrl()?>/admin">Cromos Torres</a>
					<div class="btn-group pull-right">
						<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
							<i class="icon-user"></i> 
							<?php echo $this->escape($this->user->username); ?>
							<span class="caret"></span>
						</a>
						<ul class="dropdown-menu">
							<li>
								<a href="<?php echo $this->baseUrl()?>/admin/user/changepassword">
									Cambiar contraseña
								</a>
							</li>
							<li class="divider"></li>
							<li>
								<a href="<?php echo $this->baseUrl()?>/admin/login/logout">
									Salir
								</a>
							</li>
						</ul>
					</div>
					<ul class="nav">
						<li class="dropdown">
							<a href="#"  class="dropdown-toggle" data-toggle="dropdown">
								Tienda<b class="caret"></b>
							</a>
							
							<ul class="dropdown-menu">
								<li>
									<a href="<?php echo $this->baseUrl() ?>/admin">
										Resumen
									</a>
								</li>
								<li class="divider"></li>
								<li>
                					<a href="<?php echo $this->baseUrl()?>/user/agregar">
                						Historial de Ventas
                					</a>
                				</li>
                				<li class="divider"></li>
                				<li>
									<a href="<?php echo $this->baseUrl()?>">Ir a la Tienda</a>
								</li>
							</ul>
						</li>
						<li class="dropdown">
							<a href="#"  class="dropdown-toggle" data-toggle="dropdown">
								Editoriales<b class="caret"></b>
							</a>
							<ul class="dropdown-menu">
								
								<li>
									<a href="<?php echo $this->baseUrl()?>/admin/editorial">Listar editoriales</a>
								</li>
								<li>
									<a href="<?php echo $this->baseUrl()?>/admin/editorial/insert">Agregar editorial</a>
								</li>
            				</ul>
						</li>
						<li class="dropdown">
							<a href="#"  class="dropdown-toggle" data-toggle="dropdown">
								Colecciones<b class="caret"></b>
							</a>
							<ul class="dropdown-menu">
								
								<li>
									<a href="<?php echo $this->baseUrl()?>/admin/collection">Listar colecciones</a>
								</li>
								<li>
									<a href="<?php echo $this->baseUrl()?>/admin/collection/insert">Agregar colecci&oacute;n</a>
								</li>
            				</ul>
						</li>
						<li class="dropdown">
							<a href="#"  class="dropdown-toggle" data-toggle="dropdown">
								Cromos<b class="caret"></b>
							</a>
							<ul class="dropdown-menu">
								
								<li>
									<a href="<?php echo $this->baseUrl()?>/admin/sticker">Listar cromos</a>
								</li>
								<li>
									<a href="<?php echo $this->baseUrl()?>/admin/sticker/index/action_method/insert">Agregar cromo</a>
								</li>
								<li class="divider"></li>
								<li>
									<a href="<?php echo $this->baseUrl()?>/admin/category/list">Listar categor&iacute;as</a>
								</li>
								<li>
									<a href="<?php echo $this->baseUrl()?>/admin/category/insert">Agregar categor&iacute;a</a>
								</li>
            				</ul>
						</li>
						<li class="dropdown">
							<a href="#"  class="dropdown-toggle" data-toggle="dropdown">
								&Aacute;lbumes<b class="caret"></b>
							</a>
							<ul class="dropdown-menu">
								
								<li>
									<a href="<?php echo $this->baseUrl()?>/admin/album">Listar &aacute;lbumes</a>
								</li>
								<li>
									<a href="<?php echo $this->baseUrl()?>/admin/album/insert">Agregar &aacute;lbum</a>
								</li>	
            				</ul>
						</li>
        			</ul>
        		</div>
      		</div>
    	</div> 
    	<!-- end nav -->   
    
    	<div class="container">
   			<?php echo $this->layout()->content; ?>
    	</div>
    
    	<script src="<?php echo $this->baseUrl()?>/js/jquery.js"></script>
    	<script src="<?php echo $this->baseUrl()?>/js/bootstrap-dropdown.js"></script>
      
	</body>
</html>

