<?php echo $this->doctype(); ?> 
<html lang="es">
	<head>
		<meta charset="utf-8">
		<meta name="description" content="Venta de cromos de coleccionismo antiguos y actuales. Mira nuestro catálogo">
		
		<?php echo $this->headTitle() ?>
		
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		
		<?php 
			$this->headLink()->appendStylesheet($this->baseUrl("/css/style.css"), "screen")
			                 ->appendStylesheet("http://fonts.googleapis.com/css?family=Convergence|Montserrat", "screen");
							 
			echo $this->headLink();
		?>
				
		<!--[if lt IE 9]>
		<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
	</head>
	<body>  
	    <div id="wrapper">
		<header>
			<nav class="menu">
				<div class="headContent">
					<h1>Cromos Torres</h1>
					<ul>
						<li>
							<a href="<?php echo $this->baseUrl("") ?>" 
							<?php if ($this->section == "inicio"): ?>
								class="select">
							<?php else: ?>
								class="unselect">
							<?php endif; ?>
								Inicio
							</a>
						</li>
						<li>
							<a href="#" 
							<?php if ($this->section == "editoriales"): ?>
								class="select">
							<?php else: ?>
								class="unselect">
							<?php endif; ?>
								Editoriales
							</a>
						</li>
						<li>
							<a href="#" 
							<?php if ($this->section == "albumes"): ?>
								class="select">
							<?php else: ?>
								class="unselect">
							<?php endif; ?>
								&Aacute;lbumes
							</a>
						</li>
						<li>
							<a href="#" 
							<?php if ($this->section == "carrito"): ?>
								class="select cart">
							<?php else: ?>
								class="unselect cart">
							<?php endif; ?>
								<span><img src="images/cart.png">Carrito</span>
								<?php if ($this->cartNumber > 0): ?>
									<div id="cartNumber" class="visible">
										<?php echo $this->cartNumber ?>
									</div>
								<?php endif; ?>
							</a>
						</li>
					</ul>
				</div>
			</nav>
			<aside class="info">
				<div class="headContent">
					<ul>
						<li>
							<a href="#" 
							<?php if ($this->section == "quienessomos"): ?>
								class="select">
							<?php else: ?>
								>
							<?php endif; ?>
								¿Quiénes somos?
							</a>
						</li>
						<li>
							<a href="#" 
							<?php if ($this->section == "metodospago"): ?>
								class="select">
							<?php else: ?>
								>
							<?php endif; ?>
								Métodos de pago
							</a>
						</li>
						<li>
							<a href="#" 
							<?php if ($this->section == "comprayenvio"): ?>
								class="select">
							<?php else: ?>
								>
							<?php endif; ?>
								Compra y envío
							</a>
						</li>
					</ul>
				</div>
			</aside>
		</header>

		<div id="content">
			<?php echo $this->layout()->content; ?>
		</div>
		
		<footer>
			<p><a href="">¿Quiénes somos?</a></p>
			<nav id="social">
				<ul>
					<li>
						<a href="#"><img src="images/twitter-icon.png">Twitter</a>
					</li>
					<li>
						<a href="#"><img src="images/facebook-icon.png">Facebook</a>
					</li>
					<li>
						<a href="#"><img src="images/mail-icon.png">Contacto</a>
					</li>
				</ul>
			</nav>
			<div id="credits">
				Sitio web creado por <a href="http://albertoalcolea.com">Alberto Alcolea</a>
			</div>
		</footer>
	</body>
</html>