<?php echo $this->doctype(); ?> 
<html lang="es">
    <head>
        <meta charset="utf-8">
        
        <?php echo $this->headTitle() ?>    
    
         <style type="text/css">
          body {
            padding-top: 60px;
            padding-bottom: 40px;
          }
          .sidebar-nav {
            padding: 9px 0;
          }
        </style>
        
        <?php 
			$this->headLink()->appendStylesheet($this->baseUrl("/css/bootstrap.css"), "screen")
			                 ->appendStylesheet($this->baseUrl("/css/bootstrap-responsive.css"), "screen")
			                 ->appendStylesheet($this->baseUrl("/css/admin.css"), "screen");
			
			echo $this->headLink();
		?>
    </head>
    <body>
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container-fluid">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->baseUrl("") ?>">Cromos Torres</a>
                </div>
            </div>
        </div>
        <div class="container">
            <?php echo $this->layout()->content; ?>
            
        </div><!-- fin container -->

    </body>
</html>
