
<div class="span9">
    <h1 class="page-header"><?php echo $this->title ?></h1>
    <?php if (count($this->data) == 0): ?>
		<div class="alert">
    		<p><?php echo $this->msgempty ?></p>
    	</div>
    	
    <?php else: ?>
	    <table class="table table-bordered">
	        <thead>
	            <tr>
					<th>Colecci&oacute;n</th>
	            	<th>Nombre</th>
	            	<th>Precio</th>
	            	<th>Stock</th>
	            	<th>Ver im&aacute;genes</th>
	                <th>Editar</th>
	                <th>Eliminar</th>
	            </tr>
	        </thead>
	        <tbody>
	            <?php foreach ($this->data as $album): ?>
	                <tr>
	                	<td>
	                    	<a href="<?php echo $this->baseUrl() ?>/admin/collection/update/id/<?php echo $album->getCollection()->getId(); ?>" >
								<?php echo $album->getCollection()->getName(); ?>
	                    	</a>
	                    </td>
	                	<td><?php echo $this->escape($album->getName()); ?></td>
						<td><span class="pull-right"><?php echo $this->escape($album->getPrice()); ?> &euro;</span></td>
						<td><span class="pull-right"><?php echo $this->escape($album->getStock()); ?></span></td>
	                    <td>
	                    	<a href="<?php echo $this->baseUrl() ?>/admin/album/images/album_id/<?php echo $album->getId() ?>">
	                    		<i class="icon-picture"></i>
	                    	</a>
	                    </td>
	                    <td>
	                    	<a href="<?php echo $this->baseUrl() ?>/admin/album/update/id/<?php echo $album->getId(); ?>" >
	                    		<i class="icon-edit"></i>
	                    	</a>
	                    </td>  
	                    <td>
	                    	<a href="<?php echo $this->baseUrl() ?>/admin/album/delete/id/<?php echo $album->getId(); ?>" 
	                    		onclick="return confirm('&iquest;Est&aacute; seguro que desea eliminar este &aacute;lbum?');">
	                    		<i class="icon-remove"></i>
	                    	</a>
	                    </td>
	                </tr>
	            <?php endforeach; ?>
	        </tbody>
	    </table>
	    <?php
			echo $this->paginationControl($this->data, 'Sliding', 'pagination.phtml');
		?>
	<?php endif; ?>
</div>
