<div class="row">
    <div class="span12">
        <div id="login">
            <h2><em><?php echo $this->title ?></em></h2>  
            <?php if (!$this->successful): ?>
	            <div id="main-login">
	                <div class="linea"></div>
	
	                <form action="<?php echo $this->baseUrl ?>/user/changepassword" method="post">
	                    <div class="alert-error">
	                    	<?php 
	                    		if (!empty($this->message))
	    							echo $this->message
	    					?> 
	    				</div>   
	                    <ul>
	                    	<li>
	                    		<label for="actual-pass">Contrase&ntilde;a actual</label>
	                    		<input type="password" class="input-largo"required="required" name="actual-pass" id="actual-pass" />
	                    	</li>
	                        <li> 
	                            <label for="new-pass">Nueva contrase&ntilde;a</label>
	                            <input type="password" class="input-largo" required="required" name="new-pass" id="new-pass" />
	                        </li>
	                        <li>
	                            <label for="confirm-pass">Confirmar contrase&ntilde;a</label>
	                            <input type="password" class="input-largo" required="required" name="confirm-pass" id="confirm-pass" />
	                        </li>
	
	                        <li><input type="submit" class="btn btn-large btn-inverse" value="Cambiar contrase&ntilde;a" /> 
	                        </li>
	                          
	                    </ul>
	                </form> 
	            </div>
	        <?php else: ?>
	        	<div id="main-login">
	        		<a href="<?php echo $this->baseUrl ?>/index/admin">Volver</a>
	        	</div>
	    	<?php endif; ?>
        </div><!-- fin login -->
    </div>

</div><!-- fin row -->

