
<div class="span9">
    <h1 class="page-header"><?php echo $this->title ?></h1>
    <?php if (count($this->data) == 0): ?>
    	<div class="alert" style="clear: both;">
    		<p><?php echo $this->msgempty ?></p>
    	</div>
    <?php else: ?>
	    <div>
			<form id="filterCollectionForm" name="filterCollectionForm" method="get" action="<?php echo $this->baseUrl() ?>/admin/sticker/<?php echo $this->action ?>" class="form-inline">
				<label for="collection_id">Elijar una colecci&oacute;n: </label>
				<select name="collection_id" id="collection_id">
					<?php foreach ($this->data as $collection): ?>
						<option value="<?php echo $collection->getId() ?>" label="<?php echo $collection->getName() ?>">
							<?php echo $collection->getName() ?>
						</option>
					<?php endforeach; ?>
				</select>
				<input type="submit" value="Filtrar" class="btn">
			</form>
	    </div>
	<?php endif; ?>
</div>    
